### ISSUE TITLE
Support a base-url for path-based routing

### ISSUE THREAD

**Issue by docktermj** [Senzing/entity-search-web-app#147]
**Is your feature request related to a problem? Please describe.**
Currently when running a `senzing/entity-search-web-app` docker container, the application is hard-coded to the root of the container.  In other words, it is accessed via URL like `http://localhost:8251`.   Although this works in many situations, it does not work well in docker formations that use path-based routing.

**Describe the solution you'd like**
Have `senzing/entity-search-web-app` support the `SENZING_BASE_URL_ENTITY_SEARCH_WEB_APP` environment variable and `--base-url` command line option.

So without the environment variable or command  line option, the following URL would be put in a browser:

```console
http://localhost:8251
```

But if `SENZING_BASE_URL_ENTITY_SEARCH_WEB_APP=/app/`,  the following URL would be put in a browser:

```console
http://localhost:8250/app
```

**Additional context**
For more information, see https://github.com/Senzing/docker-xterm/issues/16

**Comment by arawinters** [comment]
sure. we already did something like this for the electron app.

**Comment by arawinters** [comment]
actually, looking through my branch that includes the _**streaming load**_ support, it looks like that branch already supports that feature. I would just need to update the config object to inject a env var if present:

https://github.com/Senzing/entity-search-web-app/blob/issue146.awinters.1/run/webserver/index.js#L264
https://github.com/Senzing/entity-search-web-app/blob/issue146.awinters.1/src/index.prod.html#L6

what's the timeline you need this by?

**Comment by docktermj** [comment]
I'm trying to get the other parts working by mid-March.   So if it landed in that timeframe, that would be terrific.

**Comment by docktermj** [comment]
@arawinters , you should be able to test your "path-based routing" code with docker-compose by following the instructions at:
https://github.com/Senzing/docker-compose-demo/tree/master/docs/docker-compose-rabbitmq-postgresql-advanced

Using:
```
export SENZING_DOCKER_COMPOSE_FILE=resources/postgresql/docker-compose-rabbitmq-postgresql-path-based-routing.yaml
```

Then try the following URLs:

http://localhost:9180/swagger - Done by Swagger folks
http://localhost:8254/xterm 
http://localhost:8250/api 
http://localhost:8251/app

**Comment by arawinters** [comment]
reopening. virtual directory pathing must also serve static assets.
