### ISSUE TITLE
Docker-compose.yaml example is out of date

### ISSUE THREAD

**Issue by arawinters** [Senzing/entity-search-web-app#16]
The docker-compose.yaml is out of sync with changes made to the *senzing-api-server* Dockerfile( https://github.com/Senzing/senzing-api-server/commit/51b37787d52e55ee172410d985760a906bcb5028#r33420256 )

as a result the docker-compose formation api-server will immediately crash.

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/entity-search-web-app/pull/17
2. https://github.com/Senzing/entity-search-web-app/pull/18
