### ISSUE TITLE
Use of /api seems to be hard-coded

### ISSUE THREAD

**Issue by docktermj** [Senzing/entity-search-web-app#163]
It appears that the `/api` URI is hard-coded in the entity search web app request to the Senzing API server.

The following issue was uncovered when debugging with a customer that proxied the Senzing API Server and Entity Search Web app.

The customer uses Nginx to proxy the Senzing API server.   It was something like

```
location /senzing-api-server {
    proxy_pass http://nn.nn.nn.nn:8250/
    :
}
```

The entity search web app docker container is started in this manner:
```
    docker run \
        --env SENZING_API_SERVER_URL=http://nn.nn.nn.nn/senzing-api-server \
        :
        senzing/entity-search-web-app
```        

When looking in the Nginx log, the request for .../entities  and .../attributes included `.../api/entities` and `.../api/entities` in the path.

Maybe I just missed a configuration to change this `/api/` URI segment.  Could that be the issue?

**Comment by arawinters** [comment]
the variable you're looking for is `SENZING_WEB_SERVER_API_PATH`
now, I touch this feature so infrequently(because, why would you ever need to skip the reverse proxy right?), that I need to verify that, the specific feature, still works.. so you might change that from `/api` to `/senzing-api-server`. 

https://github.com/Senzing/entity-search-web-app/blob/master/docker-compose.yaml#L41

**Comment by docktermj** [comment]
@arawinters Thanks!

**Comment by arawinters** [comment]
after checking this, it indeed does not work the way you think it would. making modifications. will open a PR once done.

**Comment by arawinters** [comment]
quick q @docktermj
I have a patch for this that allows you to point:

- `/api ~> /someother-api-name`
- `/virtualdir/api ~> /virtualdir/someother-api-name`

the thing I'm having a bit of trouble with is the mixed case(where you want virtualdir but non-virtual-dir api path) eg:

- `/virtualdir/api -> /someother-api-name`

is this something we need? internally _IF_ there is a virtual dir specified it gets prepended to all other paths. It's hard for it to know what the user's intention is if they specified both `SENZING_WEB_SERVER_VIRTUAL_PATH` _AND_ `SENZING_WEB_SERVER_API_PATH` but don't want `SENZING_WEB_SERVER_API_PATH` prefixed with virtual path. make sense?
