### ISSUE TITLE
Add ability to compile local subrepo of SDK Components

### ISSUE THREAD

**Issue by arawinters** [Senzing/entity-search-web-app#19]
SDK components has some extra configuration that allows for pulling it in as a subrepo of another angular project for local compilation. This functionality was added for supporting streamlined workflow with the Senzing app compiling it's own special branches of the SDK components.

This same method of working with local copies of the SDK components should be added as an optional feature when working with this app to support rapid development.

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/entity-search-web-app/pull/20
