### ISSUE TITLE
Provide a list of parameters / environment variables in README.md

### ISSUE THREAD

**Issue by docktermj** [Senzing/entity-search-web-app#218]
**Is your feature request related to a problem? Please describe.**
Currently it is difficult to figure out what parameters/options are available when running the Entity Search Web App.
There's the [Configuration](https://github.com/Senzing/entity-search-web-app#configuration) section, 
but it only has variable used when bringing up Docker.

**Describe the solution you'd like**
Information on what parameters are available and example values for each parameter to help avoid "guessing" what the parameter value might be or the format of the value.

Examples:

-  SENZING_API_SERVER_URL
-  SENZING_WEB_SERVER_ADMIN_AUTH_MODE
-  SENZING_WEB_SERVER_ADMIN_AUTH_PATH
-  SENZING_WEB_SERVER_INTERNAL_URL
-  SENZING_WEB_SERVER_PORT
-  SENZING_WEB_SERVER_STREAM_CLIENT_URL
-  SENZING_WEB_SERVER_VIRTUAL_PATH

**Comment by docktermj** [comment]
@arawinters 
At least have it in the project, where it is close to the code.

**Comment by arawinters** [comment]
> For instance, what's the difference between `SENZING_WEB_SERVER_INTERNAL_URL` and `SENZING_WEB_SERVER_URL`?

I was intrigued so I looked it up. SENZING_WEB_SERVER_INTERNAL_URL: https://github.com/Senzing/entity-search-web-app/blob/master/run/runtime.datastore.config.js#L534

as far as the code is concerned they are the same thing.  (I think in the sqs development we initially needed two distinct urls, one the public FQDN, the other  the internal(behind the security gateway/formation url).. pretty sure that's deprecated.  

sure would be handy if I had a table that just said `DEPRECATED` next to that  ^_^
