### ISSUE TITLE
Add eda-tools through xterm.js functionality

### ISSUE THREAD

**Issue by arawinters** [Senzing/entity-search-web-app#242]
**Is your feature request related to a problem? Please describe.**
In order to facilitate advanced functionality(eda-tools) we should add an embedded xterm.js component in the admin section. 

**Describe the solution you'd like**

- [x] - Create xterm.js console component
- [x] - Add route to /admin/console for the xterm.js component
- [x] - Add console runtime config object to allow immutable docker container to point at xterm.js websocket console service.
- [x] - Add /config/console endpoint for app to query against so it knows if the console is enabled, where the container service is etc.
- [x] - Add nodejs xterm.js console socket service(for development/testing)

**Additional Issues**
We will need to create a separate docker container that just contains the necessary tools and the socket service that we can lock-down separately from the webapp for a production environment. 

[update 1-24-2022]
A new repository has been created to facilitate the creation of a `senzing/entity-search-webapp-console` docker image that can be optionally integrated with the webapp and house the eda tools separately from the web app to compartmentalize security concerns. see https://github.com/Senzing/entity-search-web-app-console

**Comment by docktermj** [comment]
@arawinters You probably already know this, but you might be able to glean some tips or code from https://github.com/Senzing/docker-xterm

I like this feature request!!!

**Comment by arawinters** [comment]
@docktermj I did a pathfinder spike yesterday just to make sure it was feasible first. It's pretty neat, I just need to make it all clean/professional now.

**Comment by arawinters** [comment]
crossing out the last todo item, moving it to its own ticket(#250 Add url parsing to the EDA Tools console)
