### ISSUE TITLE
fix karma/protractor tests, add .travis.yml to project

### ISSUE THREAD

**Issue by arawinters** [Senzing/entity-search-web-app#31]
We should be doing automated unit tests, e2e tests, and builds for this project. 
There is nothing really preventing us from doing the unit tests and automated build checks with travis-ci. For the e2e tests it might be a better option to add a e2e command to the Docker container/compose formation, then pass a specific flag to the container to run the e2e tests when it starts up vs. starting up just the webserver. 

This ticket is just for the arch/workflow, not for the tests themselves.  Those should be written at the time the component/feature is added so we'll have to retroactively create the ones that already exist.

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/entity-search-web-app/pull/35
