### ISSUE TITLE
Custom feature LIST shows _LIST on the webapp

### ISSUE THREAD

**Issue by bdealey** [Senzing/entity-search-web-app#336]
**Describe the bug**
I added a new feature, and in the incoming JSON message, added it as a LIST.   The _LIST shows up on the web app, which it should just display the feature name.

**To Reproduce**
Feature added via G2ConfigTool as
```
templateAdd {"feature": "SECONDARY_ALIEN_NUMBER", "template": "global_id", "behavior": "F1","comparison":"ID_COMP"}
setFeature {"feature":"SECONDARY_ALIEN_NUMBER","candidates": "Yes"}
setFeature {"feature":"SECONDARY_ALIEN_NUMBER","behavior": "FF"}
```

G2Explorer.py shows this field correctly:
![image](https://user-images.githubusercontent.com/1723167/181832064-feda071e-643b-49b7-8d6e-9dea9d5113bb.png)

But on the entity-search-web-app, it shows the feature with the _LIST prefix:
![image](https://user-images.githubusercontent.com/1723167/181832177-270f1399-e3cf-4817-b2ad-4742e86073f3.png)

Input Message (formatted as a python dict)

`{"DATA_SOURCE":"ECCIS2_MOCK","RECORD_ID":999999702, "NAME_LIST":[{"NAME_FIRST":"JACK","NAME_MIDDLE":"","NAME_LAST":"JONES"}], "DOB_LIST":[{"DATE_OF_BIRTH":"1964-11-02"}], "POB_LIST":[{"PLACE_OF_BIRTH":"MEXIC"}], "CITIZENSHIP_LIST":[{"CITIZENSHIP":"MEXIC"}], "PHONE_NUMBER": "7031234567", "GENDER_LIST":[{"GENDER":"M"}], "ALIEN_NUMBER": "678154229", "SECONDARY_ALIEN_NUMBER_LIST":[{"SECONDARY_ALIEN_NUMBER": "678154229"}], "SSN_LIST":[{"SSN_NUMBER":"444444444"}]}`
**Expected behavior**

I would like to see the label as SECONDARY_ALIEN_NUMBER on the web app instead of SECONDARY_ALIEN_NUMBER_LIST.  

Ticket created per request from Paul Lohr

**Comment by bdealey** [comment]
Looking at additional records, in many places I am seeing SECONDARY_ALIEN_NUMBER as the label.  It looks like its just in the MATCHED RECORDS section where its displaying SECONDARY_ALIEN_NUMBER_LIST

**Comment by jbutcher21** [comment]
@bdealey Sorry for the delay getting back to you on this, but it has been corrected.   I ran your data through our 3.2 release and it no longer shows SECONDARY_ALIEN_NUMBER_LIST

![image](https://user-images.githubusercontent.com/22121925/196598131-1997f127-eda7-4b11-b75e-1208c3f3cf15.png)

Please do let us know if there is anything further you need.
