### ISSUE TITLE
update sdk-components-ng to 1.0.8

### ISSUE THREAD

**Issue by arawinters** [Senzing/entity-search-web-app#46]
Expose Download as PDF function
Expose new Graph functionality

![2019-07-23_114832](https://user-images.githubusercontent.com/13721038/61738758-dc2d1e00-ad3f-11e9-98e4-83bb8ddd1afe.png)

**Comment by docktermj** [comment]
Pull requests

1. https://github.com/Senzing/entity-search-web-app/pull/51
