### ISSUE TITLE
Add preferences interface

### ISSUE THREAD

**Issue by arawinters** [Senzing/entity-search-web-app#60]
**Is your feature request related to a problem? Please describe.**
to provide a interface for users to access the SzPreferencesService options added to sdk-components-ng@1.0.9

**Describe the solution you'd like**
when user wants to change UI parameter options we should provide an interface to do so. These options provide things like the default collapsed/expanded state of entity detail sections, whether or not certain data is shown, how many nodes to display in graph etc.

this would be a _**nicer**_ interface than the sample one provided in the sdk example
![2019-09-04_121946](https://user-images.githubusercontent.com/13721038/64284365-4ecc1480-cf0e-11e9-8cc3-6b9c5de682cc.png)

**Additional context**
sdk-components-ng tickets: 
https://github.com/senzingiris/sdk-components-ng/issues/90
https://github.com/senzingiris/sdk-components-ng/issues/86

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/entity-search-web-app/pull/64
