### ISSUE TITLE
Getting error on web page

### ISSUE THREAD

**Issue by ZackHill05** [Senzing/entity-search-web-app#63]
User error, closing issue.

**Comment by docktermj** [comment]
So there are 2 port of interest:

1. [8250](https://github.com/Senzing/knowledge-base/blob/master/lists/ports-used-in-demonstrations.md#8250)
2. [8251](https://github.com/Senzing/knowledge-base/blob/master/lists/ports-used-in-demonstrations.md#8251)

The Senzing API Server, running on port 8250, currently doesn't have a `/` URI.
See [senzing-rest-api](https://github.com/Senzing/senzing-rest-api)

However the Senzing Entity Search Web app, running on port 8251, does have a `/` URI.

**Comment by ZackHill05** [comment]
@docktermj Thanks! I did a sudo docker ps and realized that right before your post :0). Now that I have the entity search up, it isn't finding anyone when I search (I'm doing a full name search). How do I figure out why the search isn't working?

**Comment by docktermj** [comment]
@ZackHill05, The first test is to look to see what's in the database. In your G2 Database, in the DSRC_RECORD or OBS_ENT tables, there should be entries.  That represents the data records sent to Senzing.

Next test,  use web browser or curl to test Senzing API server.  See "[View Senzing API](https://github.com/Senzing/docker-compose-demo/blob/master/docs/docker-compose-rabbitmq-postgresql/README.md#view-senzing-api)" for examples.  To construct more sophisticated HTTP requests, see  [senzing-rest-api](https://github.com/Senzing/senzing-rest-api)

If both of these seem to work, the next area of concern would be the network access from the Senzing Entity Search WebApp to the Senzing API server. Make sure the docker compose description of the Senzing Entity Search WebApp points to the Senzing API server correctly. [Example](https://github.com/Senzing/docker-compose-demo/blob/c72c68df7d93a84586b1f93a0538e20b859c3bcf/resources/mysql/docker-compose-rabbitmq-mysql.yaml#L164).

If none of that helps,  we bring in @arawinters to help with the next level of diagnosis.

**Comment by ZackHill05** [comment]
Looked in the database (had records) and used those records for searching. That proved the web search is working correctly. However, now I don't understand why the database doesn't have records I would have expected it to have. Out of the 12 data sources I loaded, it only has one. That's an issue with the engine, so I'll close this and put in a ticket on Senzing engine. Thanks!
