### ISSUE TITLE
Create Access control via web GUI

### ISSUE THREAD

**Issue by ZackHill05** [Senzing/entity-search-web-app#65]
While allowedOrigins would limit access from certain domains, because of the sensitivity of our data we need to have a more targeted way to limit access. Even if, for now, it was the ability to manually define a user name and password, and we'd share that with those we want to allow access to the GUI, that would work for now.

Unfortunately my management has determined that this GUI can't be used until this is addressed. A quick solution would be greatly appreciated!

**Comment by arawinters** [comment]
hi @ZackHill05 we are planning to integrate this feature in an upcoming release. I'm not 100% which release this feature is earmarked for. I'll let you know when I get a definitive response back from product planning when you can expect it.

**Comment by missulmer** [comment]
@ZackHill05 Noted.  Can I meet with you make sure we understand exactly what you're needing?

**Comment by ZackHill05** [comment]
Hi @arawinters I see that updates have been made. Can we get together to discuss the updates that have been made?

**Comment by arawinters** [comment]
Sure. I don't think these changes affect your current solution. There is an pull request that I'll be merging in shortly that adds a "standalone graph", SSL support, and a alpha implementation of basic auth. The latter two are better handled through a more robust solution if one already exists in the organization strategy, like infra-wide SSO etc.

**Comment by missulmer** [comment]
@ZackHill05 is this still a hot topic to circle back on?

**Comment by ZackHill05** [comment]
Hi Laura,

It is not a hot topic, this topic can be closed.

Thanks for reaching out and asking!

Zachery Hill
