### ISSUE TITLE
Entity detail is blank while waiting for graph api requests to complete

### ISSUE THREAD

**Issue by arawinters** [Senzing/entity-search-web-app#67]
**Describe the bug**
Page spinner does not wait for entity detail to be fully rendered before disapearing. This results in the spinner disapearing right after a search result is clicked and then presenting a blank white page with a generic icon until all the component can be fully rendered.

**To Reproduce**

1. Enter a name in search box
2. Click on a name, the spinner will briefly appear.
3. then wait another 10-XX seconds for the entity detail to render

**Expected behavior**
You click a name, spinner starts and when it dissapears the user is immediately presented with the entity detail for the result they clicked on.

**Additional context**
I'm 90% sure this bug was introduced when we either included the graph component, or when we broke the graph components out to a separate project/repo.

**Comment by arawinters** [comment]
found the issue, it's not the graph api request. it's the *withRelated=true* part of the main entityId request. I have a fix for the UI spinner waiting until the request is actually complete, as for the speed of the request response, that's a separate issue.

proposed fix:
update `this.sdkSearchService.getEntityById(entityId)` to `this.sdkSearchService.getEntityById(entityId, true)` so that the route resolver request matches the request that is defined for the actual entity detail component.
https://github.com/Senzing/entity-search-web-app/blob/master/src/app/services/entity-search.service.ts#L142

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/entity-search-web-app/pull/70
