### ISSUE TITLE
Standalone Graph, and update deps to sdk components 1.1.0

### ISSUE THREAD

**Issue by arawinters** [Senzing/entity-search-web-app#71]
- Merge in backported support for Standalone Graph, any related features. 
- Update deps to sdk-components-ng@1.1.0
- Update deps to sdk-graph-components@0.1.0
- update version to X.1.X release

![2019-11-07_130230](https://user-images.githubusercontent.com/13721038/68632981-13693b80-04a5-11ea-961d-35bff09f2b41.png)

![2019-11-07_123405](https://user-images.githubusercontent.com/13721038/68633049-4e6b6f00-04a5-11ea-894f-efbf22f70a1b.png)

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/entity-search-web-app/pull/72
