### ISSUE TITLE
Add "Admin" features. Bulk loading, data source creation.

### ISSUE THREAD

**Issue by arawinters** [Senzing/entity-search-web-app#89]
**Is your feature request related to a problem? Please describe.**
The changes for sdk-components-ng need to be integrated in to the webapp. This is to facilitate the loading/mapping/creation of datasources.
relates to: https://github.com/Senzing/sdk-components-ng/issues/133

**Describe the solution you'd like**

- Implement a new /admin route
- ~Route should be authenticated off a hashed value and a suid of "Admin". Admin user always exist but hash secret passed in through the cmdline or docker docker secret.~
- ~Route should prompt for username/password. Password should then be salted by the value passed in through the command line. Storage of the salt to be determined later.~
- ~If no secret is passed in the route should display a message about how to enable admin.~
- There should be some prominent messaging/indication that the api server is in write/admin mode when activated.
- Admin route when in admin mode should allow ~authenticated~ super user to create and load new datasources.

**Comment by docktermj** [comment]
@arawinters It seems that the authentication / authorization should be enforced by the `senzing-api-server` (https://github.com/Senzing/senzing-api-server).

The `entity-search-web-app` is a client that would support the authorization mechanism(s) of the `senzing-api-server`.

**Comment by arawinters** [comment]
currently there is no authentication support in the api server. Thus there would be no way to provide that functionality. I'm going to strike the auth related ac from the ticket pending further conversation(s).
